const CACHE_NAME = "aqua-super-pwa-v19-20260915-auto-exit-backup";
const APP_SHELL = ["./","./index.html","./manifest.webmanifest","./sw.js","./icon-192.png","./icon-512.png"];
const NOTE_FIX = `<script id="aqua-notes-click-fix">(function(){window.aquaOpenNotes=function(){try{if(typeof window.aquaNotesRender==='function'){window.aquaNotesRender();return}var m=document.getElementById('main');if(m)m.innerHTML='<div class="box"><h2>📝 Notes / اطلاع</h2><p>Notes load nahi hua. Please page refresh karein.</p></div>'}catch(e){console.error('Notes',e)}};var b=document.getElementById('nNotes');if(b)b.onclick=function(){window.aquaOpenNotes()};})();</script>`;
const INSTALL_HIDE = `<style id="aqua-install-hide">#aquaInstallBtn{display:none!important;visibility:hidden!important;height:0!important;min-height:0!important;padding:0!important;margin:0!important;border:0!important;overflow:hidden!important;pointer-events:none!important}</style>`;
const EXIT_BACKUP = `<script id="aqua-exit-auto-backup-v1">(function(){if(window.__AQUA_EXIT_AUTO_BACKUP_V1)return;window.__AQUA_EXIT_AUTO_BACKUP_V1=true;var DRIVE_URL="https://script.google.com/macros/s/AKfycbxgcIYXRDoUP7nYXrC8TzbF-hI-CTKhVncnWX7yViF97uAXBjto5nsGXvXXGjNrjdcwIQ/exec",DL="AQUA_EXIT_DOWNLOAD_DATE_V1";function today(){var d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}function snap(){try{return JSON.stringify(window.db||{customers:[],entries:[]})}catch(e){return null}}function drive(){try{var p=snap();if(!p)return;var f=document.createElement('iframe'),n='aqua_exit_'+Date.now();f.name=n;f.style.display='none';document.body.appendChild(f);var form=document.createElement('form');form.method='POST';form.action=DRIVE_URL;form.target=n;form.style.display='none';[['data',p],['date',today()],['mode','auto-exit']].forEach(function(x){var i=document.createElement('input');i.name=x[0];i.value=x[1];form.appendChild(i)});document.body.appendChild(form);form.submit();setTimeout(function(){try{form.remove();f.remove()}catch(e){}},5000)}catch(e){}}function downloadOnce(){try{var d=today();if(localStorage.getItem(DL)===d)return;var p=snap();if(!p)return;var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([p],{type:'application/json'}));a.download='Aqua Super Auto Backup - '+d+'.json';document.body.appendChild(a);a.click();a.remove();try{localStorage.setItem(DL,d)}catch(e){}setTimeout(function(){try{URL.revokeObjectURL(a.href)}catch(e){}},3000)}catch(e){}}function backup(){try{if(typeof window.aquaSaveDailyBackup==='function')window.aquaSaveDailyBackup()}catch(e){}drive();setTimeout(downloadOnce,250)}var s=window.save;if(typeof s==='function')window.save=function(){var r=s.apply(this,arguments);backup();return r};window.addEventListener('pagehide',backup);document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')backup()})})();</script>`;
async function patch(response){try{const type=response.headers.get("content-type")||"";if(!type.includes("text/html"))return response;const html=await response.text();let updated=html.replace(/<button[^>]*id=["']aquaInstallBtn["'][^>]*>[\s\S]*?<\/button>/gi,"");updated=updated.replace(/onclick=["']aquaOpenNotes\(\)["']/gi,'onclick="aquaOpenNotes()"');if(!updated.includes('id="aqua-install-hide"'))updated=updated.replace(/<\/head>/i,INSTALL_HIDE+"</head>");if(!updated.includes('id="aqua-notes-click-fix"'))updated=updated.replace(/<\/body>/i,NOTE_FIX+"</body>");if(!updated.includes('id="aqua-exit-auto-backup-v1"'))updated=updated.replace(/<\/body>/i,EXIT_BACKUP+"</body>");const h=new Headers(response.headers);h.set("content-type","text/html; charset=utf-8");h.delete("content-length");return new Response(updated,{status:response.status,statusText:response.statusText,headers:h})}catch(e){return response}}
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(APP_SHELL)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("message",e=>{if(e.data&&e.data.type==="SKIP_WAITING")self.skipWaiting()});
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const nav=e.request.mode==="navigate"||(e.request.headers.get("accept")||"").includes("text/html");if(nav){e.respondWith(fetch(e.request).then(patch).then(r=>{if(r&&r.status===200){const c=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,c)).catch(()=>{})}return r}).catch(()=>caches.match(e.request).then(r=>r?patch(r):r)));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r&&r.status===200&&r.type!=="opaque"){const cp=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,cp).catch(()=>{}))}return r}).catch(()=>c)))});