const CACHE_NAME = "aqua-super-pwa-v16-20260904-notes-fixed";
const APP_SHELL = ["./","./index.html","./manifest.webmanifest","./sw.js","./icon-192.png","./icon-512.png"];

const INJECT = `
<style id="aqua-notes-fix-style">
html,body{width:100%;max-width:none;overflow-x:hidden}
main{width:100%!important;max-width:none!important;margin:0!important;padding-left:0!important;padding-right:0!important}
#aquaInstallBtn{display:none!important}
.aqua-notes-wrap{margin:0 0 14px;padding:14px 12px 18px;background:#fff;box-shadow:0 2px 9px #0001}
.aqua-notes-title{font-size:22px;font-weight:800;color:#17324d;margin:2px 0 5px}.aqua-notes-sub{font-size:13px;color:#64748b;margin-bottom:12px}
.aqua-notes-text{width:100%;min-height:150px;padding:13px;border:1px solid #ccd8e3;border-radius:12px;font-size:16px;line-height:1.45;resize:vertical;background:#fff;box-sizing:border-box}
.aqua-notes-actions,.aqua-note-btns{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:10px 0}.aqua-notes-actions button,.aqua-note-btns button{width:100%;min-height:52px}
.aqua-note-wa{background:#16a34a!important}.aqua-note-sms{background:#2563eb!important}.aqua-note-next{background:#0ea5e9!important}
.aqua-batch{padding:11px;border-radius:12px;background:#eff6ff;border:1px solid #bfdbfe;margin:10px 0;color:#075985;font-size:13px}
.aqua-notes-search-wrap{padding:0 12px 10px;background:#fff}.aqua-notes-search{width:100%;padding:12px 14px;border:1px solid #ccd8e3;border-radius:10px;font-size:15px;background:#fff;box-sizing:border-box}
.aqua-note-customer{padding:13px 0;border-bottom:1px solid #e5edf3}.aqua-note-name{font-size:17px;font-weight:800;color:#17324d}.aqua-note-phone{font-size:12px;color:#64748b;margin-top:3px}.aqua-notes-noresult{padding:10px 0;color:#64748b;font-size:13px}
@media(max-width:360px){.aqua-notes-actions,.aqua-note-btns{grid-template-columns:1fr}}
</style>
<script id="aqua-notes-fix-script">
(function(){
function escv(v){return String(v==null?"":v).replace(/[&<>\\\"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',"'":'&#39;'}[m]||m})}
function customers(){return (window.db&&Array.isArray(db.customers)?db.customers:[]).filter(function(c){return c&&String(c.mobile||c.phone||'').replace(/\\D/g,'').length>=10})}
function phone(c){return String(c.mobile||c.phone||'').replace(/\\D/g,'')}
function message(){var e=document.getElementById('aquaNotesMessage');return e?e.value.trim():''}
function save(){try{localStorage.setItem('AQUA_SUPER_NOTES_MESSAGE_1',message())}catch(e){}}
function openOne(c,ch){var m=message();if(!m){alert('Pehle Notes message type karein.');return}var p=phone(c);if(!p){alert('Is customer ka mobile number nahi hai.');return}save();var url=ch==='wa'?'https://wa.me/91'+p+'?text='+encodeURIComponent(m):'sms:'+p+'?body='+encodeURIComponent(m);window.location.href=url}
function renderList(q){var box=document.getElementById('aquaNotesCustomerList');if(!box)return;q=String(q||'').toLowerCase().trim();var a=customers(),out='',found=0;a.forEach(function(c,i){var hay=(String(c.name||'')+' '+phone(c)).toLowerCase();if(q&&hay.indexOf(q)<0)return;found++;out+='<div class="aqua-note-customer"><div class="aqua-note-name">'+escv(c.name||'Customer')+' Ji</div><div class="aqua-note-phone">📱 '+escv(phone(c))+'</div><div class="aqua-note-btns"><button class="aqua-note-wa" onclick="aquaNotesSendWhatsApp('+i+')">📲 WhatsApp</button><button class="aqua-note-sms" onclick="aquaNotesSendSMS('+i+')">💬 SIM SMS</button></div></div>'});box.innerHTML=found?out:'<div class="aqua-notes-noresult">Is search se koi customer nahi mila.</div>'}
function batch(ch){var a=customers(),m=message();if(!m){alert('Pehle Notes message type karein.');return}if(!a.length){alert('Kisi customer ka valid mobile number nahi mila.');return}save();try{localStorage.setItem('AQUA_SUPER_NOTES_BATCH_1',JSON.stringify({channel:ch,index:0,total:a.length,message:m}))}catch(e){}openOne(a[0],ch)}
function renderBatch(){var b=document.getElementById('aquaNotesBatch');if(!b)return;var x=null;try{x=JSON.parse(localStorage.getItem('AQUA_SUPER_NOTES_BATCH_1')||'null')}catch(e){}if(!x){b.innerHTML='';return}var label=x.channel==='wa'?'WhatsApp':'SIM SMS';b.innerHTML='📨 <b>All Customer '+label+' batch:</b> '+(Number(x.index)+1)+' / '+x.total+'<br>Message open/send karne ke baad <b>Next Customer</b> dabayein.<button class="aqua-note-next" style="margin-top:9px" onclick="aquaNotesNext()">➡️ Next Customer '+label+'</button><button style="margin-top:7px;background:#64748b" onclick="aquaNotesStopBatch()">✖ Stop Batch</button>'}
window.aquaNotesNext=function(){var x=null;try{x=JSON.parse(localStorage.getItem('AQUA_SUPER_NOTES_BATCH_1')||'null')}catch(e){}if(!x)return;var a=customers(),n=Number(x.index)+1;if(n>=a.length){alert('✅ All customers batch complete.');window.aquaNotesStopBatch();return}x.index=n;x.total=a.length;try{localStorage.setItem('AQUA_SUPER_NOTES_BATCH_1',JSON.stringify(x))}catch(e){}var t=document.getElementById('aquaNotesMessage');if(t)t.value=x.message||message();openOne(a[n],x.channel);renderBatch()}
window.aquaNotesStopBatch=function(){try{localStorage.removeItem('AQUA_SUPER_NOTES_BATCH_1')}catch(e){}renderBatch()}
window.aquaNotesSendAllWhatsApp=function(){batch('wa')};window.aquaNotesSendAllSMS=function(){batch('sms')};window.aquaNotesSendWhatsApp=function(i){openOne(customers()[Number(i)],'wa')};window.aquaNotesSendSMS=function(i){openOne(customers()[Number(i)],'sms')};window.aquaNotesFilterCustomers=function(q){renderList(q)};
window.aquaNotesRender=function(){var main=document.getElementById('main'),nav=document.querySelector('nav');if(!main)return;if(nav){nav.querySelectorAll('button').forEach(function(b){b.className=''});var nb=document.getElementById('nNotes');if(nb)nb.className='active'}var saved='';try{saved=localStorage.getItem('AQUA_SUPER_NOTES_MESSAGE_1')||''}catch(e){}main.innerHTML='<div class="aqua-notes-wrap"><div class="aqua-notes-title">📝 Notes / اطلاع</div><div class="aqua-notes-sub">Plant band, gaadi breakdown, staff nahi aaya ya koi bhi update customer ko bhejein.</div><textarea id="aquaNotesMessage" class="aqua-notes-text" placeholder="Yahan apna message manually type karein..."></textarea><div class="aqua-notes-actions"><button class="aqua-note-wa" onclick="aquaNotesSendAllWhatsApp()">📲 All Customer<br>WhatsApp</button><button class="aqua-note-sms" onclick="aquaNotesSendAllSMS()">💬 All Customer<br>SIM SMS</button></div><div id="aquaNotesBatch" class="aqua-batch"></div></div><div class="aqua-notes-search-wrap"><input id="aquaNotesCustomerSearch" class="aqua-notes-search" type="search" placeholder="🔎 Customer name ya mobile number search karein..." oninput="aquaNotesFilterCustomers(this.value)" autocomplete="off"></div><div class="box" style="margin:0 12px 12px"><h2>👥 All Customers</h2><div class="small" style="margin-bottom:8px">Har customer ko Notes message alag se WhatsApp ya SIM SMS kar sakte hain.</div><div id="aquaNotesCustomerList"></div></div>';var t=document.getElementById('aquaNotesMessage');if(t){t.value=saved;t.addEventListener('input',save)}renderList('');renderBatch()}
window.aquaOpenNotes=function(){if(typeof window.aquaNotesRender==='function'){window.aquaNotesRender()}else{var m=document.getElementById('main');if(m)m.innerHTML='<div class="box"><h2>📝 Notes / اطلاع</h2><p>Notes load nahi hua. Please app ko ek baar refresh karein.</p></div>'}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){window.aquaOpenNotesReady=true});
})();
</script>`;

async function inject(response){try{const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;const html=await response.text();if(html.includes('id="aqua-notes-fix-script"'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});const updated=html.replace(/<\\/head>/i,INJECT.split('</head>')[0]+'</head>').replace(/<\\/body>/i,INJECT+'</body>');const h=new Headers(response.headers);h.set('content-type','text/html; charset=utf-8');h.delete('content-length');return new Response(updated,{status:response.status,statusText:response.statusText,headers:h})}catch(e){return response}}

self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(APP_SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const nav=e.request.mode==='navigate'||(e.request.headers.get('accept')||'').includes('text/html');if(nav){e.respondWith(fetch(e.request).then(inject).then(r=>{if(r&&r.status===200){const c=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,c)).catch(()=>{})}return r}).catch(()=>caches.match(e.request)));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r&&r.status===200&&r.type!=='opaque'){const cp=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,cp)).catch(()=>{})}return r}).catch(()=>c)))});
